# -*- coding: utf-8 -*-
# Generated by Django 1.9b1 on 2016-07-25 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='weixin',
            fields=[
                ('flag', models.IntegerField(null=True)),
                ('uid', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('contenthe', models.TextField(null=True)),
                ('contentme', models.TextField(null=True)),
            ],
        ),
    ]
